name = "picodeck-store"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = false

routes = [{ pattern = "store.picodeck.net", custom_domain = true }]

[[r2_buckets]]
binding = "STORE_BUCKET"
bucket_name = "picodeck-store"

[[kv_namespaces]]
binding = "STORE_KV"
id = "1518855e23594d3ea3db8703f51c8ccf"

[triggers]
crons = ["*/30 * * * *"]

[observability]
enabled = true
